### ISSUE TITLE
A java.lang.NumberFormatException bug

### ISSUE THREAD

**Issue by ywm0822** [ZorgeR/nanoConverter#3]
## Hello,we find a java.lang.NumberFormatException bug when we are testing your app with an automated GUI testing tool developed by us.Here is a piece of the execution log:

E/AndroidRuntime( 2928): FATAL EXCEPTION: main
E/AndroidRuntime( 2928): Process: a3e.process, PID: 2928
E/AndroidRuntime( 2928): java.lang.RuntimeException: Unable to resume activity {com.nanoconverter.zlab/com.nanoconverter.zlab.NanoConverter}: java.lang.NumberFormatException: Invalid double: "1.0000test"
E/AndroidRuntime( 2928):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2799)
E/AndroidRuntime( 2928):    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2828)
E/AndroidRuntime( 2928):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2263)
E/AndroidRuntime( 2928):    at android.app.ActivityThread.access$800(ActivityThread.java:147)
E/AndroidRuntime( 2928):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
E/AndroidRuntime( 2928):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2928):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2928):    at android.app.ActivityThread.main(ActivityThread.java:5135)
E/AndroidRuntime( 2928):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2928):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2928):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/AndroidRuntime( 2928):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
E/AndroidRuntime( 2928):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 2928): Caused by: java.lang.NumberFormatException: Invalid double: "1.0000test"
E/AndroidRuntime( 2928):    at java.lang.StringToReal.invalidReal(StringToReal.java:63)
E/AndroidRuntime( 2928):    at java.lang.StringToReal.initialParse(StringToReal.java:114)
E/AndroidRuntime( 2928):    at java.lang.StringToReal.parseDouble(StringToReal.java:263)
E/AndroidRuntime( 2928):    at java.lang.Double.parseDouble(Double.java:295)
E/AndroidRuntime( 2928):    at com.nanoconverter.zlab.NanoConverter.UpdateRates(NanoConverter.java:1354)
E/AndroidRuntime( 2928):    at com.nanoconverter.zlab.NanoConverter.onResume(NanoConverter.java:310)
E/AndroidRuntime( 2928):    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
E/AndroidRuntime( 2928):    at android.app.Activity.performResume(Activity.java:5440)
E/AndroidRuntime( 2928):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2789)
## E/AndroidRuntime( 2928):    ... 12 more

The GUI testing tool will input a string"1.0000test" in the "Enter amount" textfield, and could you please take a look and confirm this bug? Thanks a lot!
ywm0822  AT gmail DOT com

**Comment by ZorgeR** [comment]
Will be checked.
